const { app, BrowserWindow, ipcMain } = require('electron') // Added ipcMain
const Store = require('electron-store'); // Added electron-store

// Store.initRenderer(); // Initialize for renderer process access -- Line Removed

let store; // Declare store variable

function createWindow () {
  store = new Store(); // Initialize store

  // Example: Save a value
  store.set('appInfo.lastOpened', new Date().toISOString());

  // Example: Load a value
  // const lastOpened = store.get('appInfo.lastOpened'); // Keep or remove as per preference
  // console.log('Last opened:', lastOpened);

  const win = new BrowserWindow({
    width: 1200, // Increased width for better layout
    height: 800, // Increased height
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false, // Be cautious with this in production
      // preload: path.join(__dirname, 'preload.js') // Optional: if you want to use a preload script
    }
  })

  win.loadFile('dist/index.html') // Load the HTML file generated by Webpack
}

app.whenReady().then(() => {
  createWindow()

  // Remove generic store IPC handlers if Store.initRenderer() is working well
  // Or keep them if there's a specific use case for direct IPC-based store access.
  // For this subtask, they are not strictly needed for export.
  // ipcMain.handle('electron-store-get', async (event, key) => {
  //   return store.get(key);
  // });
  // ipcMain.handle('electron-store-set', async (event, key, value) => {
  //   store.set(key, value);
  // });

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// --- IPC Handlers for File Export ---
const fs = require('fs');
const { dialog } = require('electron');

ipcMain.on('handle-export-json', async (event, { defaultFilename, data, fileType }) => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    console.error("No focused window to show save dialog.");
    return;
  }
  
  const { filePath } = await dialog.showSaveDialog(focusedWindow, {
    title: 'Export Project as JSON',
    defaultPath: defaultFilename,
    filters: [{ name: 'JSON Files', extensions: ['json'] }]
  });

  if (filePath) {
    try {
      fs.writeFileSync(filePath, data, 'utf-8');
      console.log(`Project exported as JSON to: ${filePath}`);
      // Optionally, send a success message back to renderer
      // event.sender.send('export-json-success', filePath);
    } catch (err) {
      console.error('Failed to save JSON file:', err);
      // Optionally, send an error message back
      // event.sender.send('export-json-error', err.message);
    }
  }
});

ipcMain.on('handle-export-csv', async (event, { defaultFilename, data, fileType }) => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    console.error("No focused window to show save dialog.");
    return;
  }

  const { filePath } = await dialog.showSaveDialog(focusedWindow, {
    title: 'Export Tasks as CSV',
    defaultPath: defaultFilename,
    filters: [{ name: 'CSV Files', extensions: ['csv'] }]
  });

  if (filePath) {
    try {
      fs.writeFileSync(filePath, data, 'utf-8');
      console.log(`Tasks exported as CSV to: ${filePath}`);
    } catch (err) {
      console.error('Failed to save CSV file:', err);
    }
  }
});
